apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
  name: rfe-tarball-pipeline
spec:
  params:
    - name: blueprints-git-url
      description: Blueprint Repository URL
      default: https://github.com/redhat-cop/rhel-edge-automation-arch.git
      type: string
    - name: blueprints-git-revision
      description: Blueprint Repository URL Reference
      default: blueprints
      type: string
    - name: tooling-git-url
      description: Tooling Repository URL
      default: https://github.com/redhat-cop/rhel-edge-automation-arch.git
      type: string
    - name: tooling-git-revision
      description: Tooling Repository URL Reference
      default: main
      type: string
    - name: blueprint-dir
      description: Directory in Blueprints repository containing blueprint
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: git-clone-tooling
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.tooling-git-url)
        - name: revision
          value: $(params.tooling-git-revision)
        - name: subdirectory
          value: "tooling"
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: git-clone-blueprints
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.blueprints-git-url)
        - name: revision
          value: $(params.blueprints-git-revision)
        - name: subdirectory
          value: "blueprints"
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-rfe-tarball
      taskRef:
        name: build-rfe-tarball
        kind: Task
      params:
        - name: blueprint-dir
          value: /workspace/workspace/blueprints/$(params.blueprint-dir)
      runAfter:
        - "git-clone-blueprints"
        - "git-clone-tooling"
      workspaces:
        - name: workspace
          workspace: shared-workspace
    - name: download-upload-rfe-tarball
      taskRef:
        name: download-upload-rfe
        kind: Task
      params:
        - name: build-commit
          value: $(tasks.build-rfe-tarball.results.build-commit)
        - name: build-dir
          value: /workspace/workspace/build
        - name: extra-ansible-variables
          value: "-e httpd_unarchive_file=true -e httpd_dest_dir=tarballs/$(tasks.build-rfe-tarball.results.build-commit)"
      runAfter:
        - "build-rfe-tarball"
      workspaces:
        - name: workspace
          workspace: shared-workspace
  results:
    - name: artifact-repository-storage-url
      description: Location where the asset is stored in the artifact repository
      value: $(tasks.download-upload-rfe-tarball.results.artifact-repository-storage-url)
    - name: serving-storage-url
      description: Location where the asset is served
      value: $(tasks.download-upload-rfe-tarball.results.serving-storage-url)
