apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
  name: rfe-oci-quay-repository
spec:
  workspaces:
    - name: workspace
  params:
    - name: blueprint-dir
      description: Directory Contaning blueprint.toml File
      type: string
    - name: repository-name
      description: Name of the Quay Repository
      type: string
  results:
    - name: image-path
      description: Path to Container Image
  steps:
    - name: create-quay-repository-playbook
      image: image-registry.openshift-image-registry.svc:5000/rfe/ansible-rfe-runner:latest
      workingDir: /workspace/workspace
      args:
        - |-
          cd tooling/ansible
          ansible-galaxy collection install -r collections/requirements.yaml
          ansible-playbook playbooks/oci-create-repository.yaml \
            -e quay_repository_name=$(params.repository-name) \
            -e quay_image_path_output_file=$(results.image-path.path)
      command:
        - /bin/bash
        - -c
      volumeMounts:
        - name: publisher
          mountPath: /var/secrets/publisher
          readOnly: true
        - name: quay-rfe-setup
          mountPath: /var/secrets/quay-rfe-setup
          readOnly: true
  volumes:
    - name: publisher
      secret:
        secretName: publisher
        defaultMode: 0440
    - name: quay-rfe-setup
      secret:
        secretName: quay-rfe-setup
        defaultMode: 0440
