apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../../../manifests/argocd/apps/auth/base
  - ../../../manifests/argocd/apps/catalogsources/base
  - ../../../manifests/argocd/apps/rbac/base
  - ../../../manifests/argocd/apps/sealed-secrets/base
  - ../../../manifests/argocd/apps/user-workload-monitoring/base
  - ../../../manifests/argocd/apps/cnv/base
  - ../../../manifests/argocd/apps/pipelines/base
