apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../environments/overlays/configs

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: config-auth
    path: auth-app-patch.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: config-rbac
    path: rbac-app-patch.yaml
