apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-locker-oauth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-locker-oauth-role
subjects:
  - kind: ServiceAccount
    name: resource-locker-oauth-sa
    namespace: resource-locker-operator
