apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: resource-locker-operator
  namespace: resource-locker-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: resource-locker-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
